# Generated by Django 2.2.4 on 2021-01-08 02:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageLink',
            fields=[
                ('url', models.TextField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('url', models.TextField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('content', models.TextField(blank=True, null=True)),
                ('pagerank', models.FloatField(default=0)),
                ('created_at', models.DateTimeField()),
                ('last_indexed', models.DateTimeField()),
                ('link', models.ManyToManyField(to='search_engine.PageLink')),
            ],
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField()),
                ('tf', models.FloatField(default=0)),
                ('idf', models.FloatField(default=0)),
                ('tfidf', models.FloatField(default=0)),
                ('score', models.FloatField(default=0)),
                ('last_idf', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_tfidf', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_scored', models.DateTimeField(default=django.utils.timezone.now)),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='search_engine.Page')),
            ],
            options={
                'unique_together': {('page', 'word')},
            },
        ),
    ]
