# Generated by Django 2.2.4 on 2021-01-09 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0002_auto_20210107_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='link',
        ),
        migrations.CreateModel(
            name='PageConnect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_engine.PageLink')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_engine.Page')),
            ],
            options={
                'unique_together': {('url', 'link')},
            },
        ),
    ]
