# Generated by Django 2.2.4 on 2021-01-12 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0003_auto_20210108_2131'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='index',
            unique_together=set(),
        ),
    ]
