# Generated by Django 2.2.4 on 2021-01-13 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0004_auto_20210112_1502'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='index',
            unique_together={('page', 'word')},
        ),
    ]
