# Generated by Django 2.2.4 on 2021-01-14 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0005_auto_20210113_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
